# Form implementation generated from reading ui file 'word-champion_game.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 616)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_timeleft = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_timeleft.setObjectName("label_timeleft")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_timeleft)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_passedcount = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_passedcount.setObjectName("label_passedcount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_passedcount)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.label_skippedcount = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_skippedcount.setObjectName("label_skippedcount")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_skippedcount)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.label_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.verticalLayout_2.addWidget(self.label_image)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_skip = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_skip.setObjectName("pushButton_skip")
        self.pushButton_skip.setStyleSheet("background-color: yellow;")
        self.horizontalLayout_2.addWidget(self.pushButton_skip)
        self.pushButton_pass = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_pass.setObjectName("pushButton_pass")
        self.pushButton_pass.setStyleSheet("background-color: green;")
        self.horizontalLayout_2.addWidget(self.pushButton_pass)
        self.pushButton_abort = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.pushButton_abort.setStyleSheet("background-color: red;")
        self.horizontalLayout_2.addWidget(self.pushButton_abort)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Word Champion - Level - Countdown"))
        self.label_2.setText(_translate("MainWindow", "Time left(Seconds)"))
        self.label_timeleft.setText(_translate("MainWindow", "timeleft"))
        self.label.setText(_translate("MainWindow", "Passed"))
        self.label_passedcount.setText(_translate("MainWindow", "passedcount"))
        self.label_5.setText(_translate("MainWindow", "Skipped"))
        self.label_skippedcount.setText(_translate("MainWindow", "skippedcount"))
        self.label_image.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_skip.setText(_translate("MainWindow", "Skip"))
        self.pushButton_pass.setText(_translate("MainWindow", "Pass"))
        self.pushButton_abort.setText(_translate("MainWindow", "Abort"))
